apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 30007
      port: 5000
      targetPort: 5000